### ISSUE TITLE
inserire nella migrazione l'anno uscita del album

### ISSUE THREAD

**Issue by EugeniuPeruzzi** [EugeniuPeruzzi/laravel-music-albums#5]

**Comment by jaupi98** [comment]
task eseguita colonna aggiunta e seeder

**Comment by michelecanini** [comment]
task eseguita con aggiunta di una variabile che comprende anche l'anno e che normalmente si trova all'interno degli album musicali (data di pubblicazione) con aggiunta colonna e seeder.
